import { createHash } from "node:crypto";

import ar from "@/data/generated/i18n/reviews.ar.json";
import bg from "@/data/generated/i18n/reviews.bg.json";
import de from "@/data/generated/i18n/reviews.de.json";
import es from "@/data/generated/i18n/reviews.es.json";
import fa from "@/data/generated/i18n/reviews.fa.json";
import fr from "@/data/generated/i18n/reviews.fr.json";
import he from "@/data/generated/i18n/reviews.he.json";
import it from "@/data/generated/i18n/reviews.it.json";
import nl from "@/data/generated/i18n/reviews.nl.json";
import ru from "@/data/generated/i18n/reviews.ru.json";
import tr from "@/data/generated/i18n/reviews.tr.json";
import uk from "@/data/generated/i18n/reviews.uk.json";
import zh from "@/data/generated/i18n/reviews.zh.json";

import type { GoogleReview } from "@/lib/reviews";

// Per-review text translation overlay: each reviews.<code>.json pack
// translates the real review text (and, when present, the clinic's reply)
// into that locale, keyed by review id + a hash of the source text/reply —
// a faithful port of scripts/build-site.mjs's reviewLoc()/shortHash(). This
// is intentionally separate from GoogleReview.translatedText (Google's own
// auto-translation, always English on this dataset): this overlay instead
// translates the review into whichever of the 13 site locales is being
// viewed, so a French visitor reads a French translation of a Turkish
// review, not an English one.
interface RawReviewLocItem {
  text?: string;
  reply?: string;
  src?: string;
  srcText?: string;
  srcReply?: string;
  translated?: boolean;
}

interface RawReviewLocPack {
  items: Record<string, RawReviewLocItem>;
}

const PACKS: Record<string, RawReviewLocPack> = {
  ar,
  bg,
  de,
  es,
  fa,
  fr,
  he,
  it,
  nl,
  ru,
  tr,
  uk,
  zh,
} as unknown as Record<string, RawReviewLocPack>;

export interface ReviewLocalization {
  text: string;
  translated: boolean;
  reply: string;
}

// sha1, first 12 hex chars — matches build-site.mjs's shortHash() exactly, so
// entries generated by the same repo tooling validate here unchanged.
function shortHash(...parts: string[]): string {
  return createHash("sha1").update(parts.join(" ")).digest("hex").slice(0, 12);
}

const reviewTextHash = (r: GoogleReview) => shortHash(r.originalText || "");
const reviewReplyHash = (r: GoogleReview) => shortHash(r.ownerReply || "");
// Legacy single-hash entries (this repo's current reviews.<code>.json packs)
// covered text + reply together, so a review with no reply at import time
// also has to validate against a hash computed with an empty reply.
const legacyHash = (r: GoogleReview) => shortHash(r.originalText || "", r.ownerReply || "");
const legacyHashNoReply = (r: GoogleReview) => shortHash(r.originalText || "", "");

// Returns the localized text/reply for a review in a given locale, or null
// when there's no entry or the source text has since changed (a stale
// translation must never be shown against different source text — the card
// falls back to the review exactly as written on Google, English UI text
// aside). English has no overlay (it *is* the source language).
export function getReviewLocalization(
  locale: string,
  review: GoogleReview,
): ReviewLocalization | null {
  const pack = PACKS[locale];
  if (!pack) return null;
  const rt = pack.items[review.id];
  if (!rt) return null;

  const textOk = rt.srcText
    ? rt.srcText === reviewTextHash(review)
    : rt.src === legacyHash(review) || rt.src === legacyHashNoReply(review);
  if (!textOk) return null;

  const replyOk = rt.srcReply ? rt.srcReply === reviewReplyHash(review) : rt.src === legacyHash(review);

  return {
    text: rt.text || "",
    translated: !!rt.translated,
    // A stale reply translation must never be shown next to a different
    // reply — drop it and the card falls back to the reply as written.
    reply: replyOk ? rt.reply || "" : "",
  };
}

export interface LocalizedReview extends GoogleReview {
  localizedText?: string;
  localizedTranslated?: boolean;
  localizedReply?: string;
}

// Attaches each review's localization for `locale` (matching the
// `localizedText`/`localizedTranslated`/`localizedReply` fields build-site.mjs
// embeds in its client-side reviews-data island). This calls into node:crypto
// (getReviewLocalization), so it must run server-side — call it from a server
// component and pass the resulting plain data down to client components,
// never import this module from a "use client" file.
export function withReviewLocalization(
  reviews: GoogleReview[],
  locale: string,
): LocalizedReview[] {
  return reviews.map((review) => {
    const loc = getReviewLocalization(locale, review);
    if (!loc) return review;
    return {
      ...review,
      localizedText: loc.text,
      localizedTranslated: loc.translated,
      localizedReply: loc.reply,
    };
  });
}
